server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: record-inventory
  lifecycle:
    timeout-per-shutdown-phase: 15s
  datasource:
    url: jdbc:postgres:localhost:5432/record-inventory
    username: user
    password: password
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh, info, health
  security:
    enabled: false